version: "3"
services:
  mongodb:
    image: tozd/meteor-mongodb:3.4
    # env_file: development.env
    env_file: production.env
  meteor:
    build: .
    # env_file: development.env
    env_file: production.env
    ports:
      - 80:3000
    links:
      - mongodb
  # orthanc:
  #   image: jodogne/orthanc-plugins:1.3.2
  #   volumes:
  #     - /temp/orthanc-db/:/var/lib/orthanc/db/
  #     - ./orthanc.json:/etc/orthanc/orthanc.json
  #   ports:
  #     - 4242:4242
  #     - 8042:8042
